FROM buildpack-deps:jessie
MAINTAINER Chris McKnight <cmckni3@gmail.com>

ENV NODE_VERSION 8.x
ENV RUBY_MAJOR 2.2
ENV RUBY_VERSION 2.2.5
ENV RUBY_BUILD_TMPDIR /tmp/ruby-build
ENV RUBY_BUILD_DIR /usr/src/ruby-build
ENV RUBYGEMS_VERSION 2.6.4

RUN apt-get update
# Install nodejs
RUN curl --silent --location https://deb.nodesource.com/setup_${NODE_VERSION} | bash - \
    && apt-get install --yes nodejs
# Install ruby
RUN git clone --quiet https://github.com/sstephenson/ruby-build.git $RUBY_BUILD_DIR \
    && ${RUBY_BUILD_DIR}/install.sh \
    && TMPDIR=$RUBY_BUILD_TMPDIR ruby-build $RUBY_VERSION /usr \
    && gem update --system $RUBYGEMS_VERSION \
    && rm -rf $RUBY_BUILD_DIR \
    && rm -rf /tmp/*.log \
    && rm -rf $RUBY_BUILD_TMPDIR

# skip installing gem documentation
RUN mkdir -p /usr/local/etc \
	&& { \
		echo 'install: --no-document'; \
		echo 'update: --no-document'; \
	} >> /usr/local/etc/gemrc

ENV BUNDLER_VERSION 1.11.2

RUN gem install bundler --version "$BUNDLER_VERSION"
